sudo: required 

services:
    -docker

before_install:
    - docker build -t jdpowers/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true jdpowers/react-test npm test 
    
after-success: 
    - docker build -t jdpowers/multi-client ./client 
    - docker build -t jdpowers/multi-nginx ./nginx
    - docker build -t jdpowers/multi-worker ./worker
    - docker build -t jdpowers/multi-server ./server 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jdpowers/multi-client
    - docker push jdpowers/multi-nginx
    - docker push jdpowers/multi-server
    - docker push jdpowers/multi-worker
    
    

deploy:
    edge: true
    provider: elasticbeanstalk 
    region: us-east-2
    app: multi-docker
    env: NultiDocker-env
    bucket_name: elasticbeanstalk-us-east-2-172423524207
    bucket_path: docker-multi
    on: 
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    